/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp5 {
  MyFlutterApp5._();

  static const _kFontFam = 'MyFlutterApp5';

  static const IconData alter = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData qrcode = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cart = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData task = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData order = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData share1 = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData inforation = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData delete = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData message1 = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData kefu = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData moeny = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData book = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData vip = IconData(0xe814, fontFamily: _kFontFam);
}
